name: Generate YAML Rules

on:
  push:
    paths:
      - 'rule/*.list'
  workflow_dispatch:

jobs:
  generate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate YAML from LIST files
        run: |
          FILES=("Custom_Direct" "Custom_Proxy" "Steam_CDN")

          for base_name in "${FILES[@]}"; do
            list_file="rule/${base_name}.list"
            domain_yaml_file="rule/${base_name}_Domain.yaml"
            ip_yaml_file="rule/${base_name}_IP.yaml"
            classical_yaml_file="rule/${base_name}_Classical.yaml"

            timestamp=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')

            # 生成规则内容
            domain_rules=$(grep -E '^(DOMAIN-|DOMAIN-SUFFIX|DOMAIN-KEYWORD)' "$list_file" | sed -E "s/^DOMAIN-SUFFIX,(.+)/  - '+.\1'/" | sed -E "s/^DOMAIN-KEYWORD,(.+)/  - '*\1*'/" | sed -E "s/^DOMAIN,(.+)/  - '\1'/")
            ip_rules=$(grep -E '^(IP-|IP-CIDR)' "$list_file" | sed -E "s/^IP-CIDR,([^,]+).*/  - '\1'/" | sed -E "s/^IP,([^,]+).*/  - '\1'/")
            classical_domain_rules=$(grep -E '^(DOMAIN-|DOMAIN-SUFFIX|DOMAIN-KEYWORD)' "$list_file" | sed -E "s/^(.*)/  - \1/")
            classical_ip_rules=$(grep -E '^(IP-|IP-CIDR)' "$list_file" | sed -E "s/^IP-CIDR,([^,]+).*/  - IP-CIDR,\1,no-resolve/" | sed -E "s/^IP,([^,]+).*/  - IP-CIDR,\1,no-resolve/")

            domain_count=$(echo "$domain_rules" | grep -c '  - ' || true)
            ip_count=$(echo "$ip_rules" | grep -c '  - ' || true)
            classical_total=$((domain_count + ip_count))

            generate_file() {
              local file="$1"
              local content="$2"
              local total="$3"
              local temp_file="${file}.tmp"

              # 先写到临时文件
              echo "# Generated from ${list_file}" > "$temp_file"
              echo "# REPO: https://github.com/Aethersailor/Custom_OpenClash_Rules" >> "$temp_file"
              echo "# SOURCE: https://github.com/Aethersailor/Custom_OpenClash_Rules/blob/main/${list_file}" >> "$temp_file"
              echo "# UPDATE: ${timestamp}" >> "$temp_file"
              echo "# TOTAL: ${total}" >> "$temp_file"
              echo "" >> "$temp_file"
              echo "payload:" >> "$temp_file"
              echo "$content" >> "$temp_file"

              # 如果内容无变化，只更新时间，不提交
              if cmp -s "$temp_file" "$file"; then
                echo "No changes in ${file}, skip commit."
                rm "$temp_file"
              else
                mv "$temp_file" "$file"
                git add "$file"
                short_file="$(basename "$file")"
                git commit -m "Generate ${short_file} from $(basename "$list_file")"
              fi
            }

            generate_file "$domain_yaml_file" "$domain_rules" "$domain_count"
            generate_file "$ip_yaml_file" "$ip_rules" "$ip_count"
            generate_file "$classical_yaml_file" "$classical_domain_rules
$classical_ip_rules" "$classical_total"

          done

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git log origin/main..HEAD) ]]; then
            git push origin HEAD:main
          else
            echo "No new commits to push."
          fi
