name: Generate YAML Rules

on:
  push:
    paths:
      - 'rule/*.list'
  workflow_dispatch:

jobs:
  generate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate YAML from LIST files
        run: |
          FILES=("Custom_Direct" "Custom_Proxy" "Steam_CDN")

          for base_name in "${FILES[@]}"; do
            list_file="rule/${base_name}.list"

            declare -A files=(
              ["${base_name}_Domain.yaml"]="$(grep -E '^(DOMAIN-|DOMAIN-SUFFIX|DOMAIN-KEYWORD)' "$list_file" | sed -E "s/^DOMAIN-SUFFIX,(.+)/  - '+.\1'/" | sed -E "s/^DOMAIN-KEYWORD,(.+)/  - '*\1*'/" | sed -E "s/^DOMAIN,(.+)/  - '\1'/")"
              ["${base_name}_IP.yaml"]="$(grep -E '^(IP-|IP-CIDR)' "$list_file" | sed -E "s/^IP-CIDR,([^,]+).*/  - '\1'/" | sed -E "s/^IP,([^,]+).*/  - '\1'/")"
              ["${base_name}_Classical.yaml"]="$(grep -E '^(DOMAIN-|DOMAIN-SUFFIX|DOMAIN-KEYWORD)' "$list_file" | sed -E "s/^(.*)/  - \1/")
$(grep -E '^(IP-|IP-CIDR)' "$list_file" | sed -E "s/^IP-CIDR,([^,]+).*/  - IP-CIDR,\1,no-resolve/" | sed -E "s/^IP,([^,]+).*/  - IP-CIDR,\1,no-resolve/")"
            )

            for yaml_file in "${!files[@]}"; do
              content="${files[$yaml_file]}"
              count=$(echo "$content" | grep -c '  - ' || true)

              echo "# Generated from ${list_file}" > "rule/$yaml_file"
              echo "# REPO: https://github.com/Aethersailor/Custom_OpenClash_Rules" >> "rule/$yaml_file"
              echo "# SOURCE: https://github.com/Aethersailor/Custom_OpenClash_Rules/blob/main/${list_file}" >> "rule/$yaml_file"
              echo "# TOTAL: ${count}" >> "rule/$yaml_file"
              echo "" >> "rule/$yaml_file"
              echo "payload:" >> "rule/$yaml_file"
              echo "$content" >> "rule/$yaml_file"

              if [[ -n $(git status --porcelain "rule/$yaml_file") ]]; then
                git add "rule/$yaml_file"
                git commit -m "Generate $(basename "$yaml_file") from $(basename "$list_file")"
              else
                echo "No changes in $yaml_file, skip commit."
              fi
            done
          done

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git log origin/main..HEAD) ]]; then
            git push origin HEAD:main
          else
            echo "No new commits to push."
          fi
