name: Protect CFG Directory Branch

on:
  push:
    paths:
      - 'cfg/**'

jobs:
  check-and-block:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if push is from GitHub Actions or repository owner
        id: check-actor
        run: |
          # Get the list of changed cfg files
          changed_cfg_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^cfg/" || echo "")
          
          # Check if only Custom_Clash_Full.ini is being modified
          if [[ "$changed_cfg_files" == "cfg/Custom_Clash_Full.ini" ]]; then
            echo "is_allowed=true" >> $GITHUB_OUTPUT
            echo "reason=excluded_file" >> $GITHUB_OUTPUT
          elif [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
            echo "is_allowed=true" >> $GITHUB_OUTPUT
            echo "reason=github_actions" >> $GITHUB_OUTPUT
          elif [[ "${{ github.actor }}" == "Aethersailor" ]]; then
            echo "is_allowed=true" >> $GITHUB_OUTPUT
            echo "reason=repository_owner" >> $GITHUB_OUTPUT
          else
            echo "is_allowed=false" >> $GITHUB_OUTPUT
            echo "reason=unauthorized_user" >> $GITHUB_OUTPUT
          fi
          
          echo "Push author: ${{ github.actor }}"
          echo "Changed cfg files: $changed_cfg_files"
          echo "Is allowed: ${{ steps.check-actor.outputs.is_allowed }}"
          echo "Reason: ${{ steps.check-actor.outputs.reason }}"

      - name: Block unauthorized pushes
        if: steps.check-actor.outputs.is_allowed == 'false'
        run: |
          echo "🚫 Blocking push to ${{ github.ref }}"
          echo "Reason: Unauthorized user trying to modify /cfg directory"
          echo "Only GitHub Actions and repository owner can modify files in the /cfg directory"
          
          # Create a status check that will fail
          echo "## ❌ Push Blocked" > status.md
          echo "" >> status.md
          echo "This push has been automatically blocked because it contains modifications to files in the `/cfg` directory." >> status.md
          echo "" >> status.md
          echo "### Why was this blocked?" >> status.md
          echo "- Direct modifications to `/cfg` directory files are not allowed for unauthorized users" >> status.md
          echo "- Only GitHub Actions workflows and repository owner can modify files in this directory" >> status.md
          echo "- This ensures configuration integrity and prevents manual errors" >> status.md
          echo "" >> status.md
          echo "### What should you do?" >> status.md
          echo "- If you need to modify configuration files, please update the source files instead" >> status.md
          echo "- The GitHub Actions workflows will automatically generate the appropriate `/cfg` files" >> status.md
          echo "- If you believe this block is in error, please contact the repository maintainers" >> status.md
          
          # Exit with error to fail the workflow
          exit 1

      - name: Allow authorized pushes
        if: steps.check-actor.outputs.is_allowed == 'true'
        run: |
          echo "✅ Allowing push to ${{ github.ref }}"
          echo "Reason: This push was created by ${{ steps.check-actor.outputs.reason }}"
          
          # Create a status check that will pass
          echo "## ✅ Push Allowed" > status.md
          echo "" >> status.md
          if [[ "${{ steps.check-actor.outputs.reason }}" == "github_actions" ]]; then
            echo "This push has been automatically allowed because it was created by GitHub Actions." >> status.md
            echo "" >> status.md
            echo "### Why was this allowed?" >> status.md
            echo "- This push was created by a GitHub Actions workflow" >> status.md
            echo "- Automated updates to `/cfg` directory are permitted" >> status.md
            echo "- The changes are part of the automated configuration generation process" >> status.md
          elif [[ "${{ steps.check-actor.outputs.reason }}" == "excluded_file" ]]; then
            echo "This push has been allowed because it only modifies Custom_Clash_Full.ini." >> status.md
            echo "" >> status.md
            echo "### Why was this allowed?" >> status.md
            echo "- Custom_Clash_Full.ini is excluded from protection rules" >> status.md
            echo "- This file can be modified by any user" >> status.md
            echo "- Other /cfg directory files remain protected" >> status.md
          else
            echo "This push has been allowed because it was created by the repository owner." >> status.md
            echo "" >> status.md
            echo "### Why was this allowed?" >> status.md
            echo "- This push was created by the repository owner" >> status.md
            echo "- Repository owners have full access to modify files in this directory" >> status.md
            echo "- Manual modifications by the owner are permitted" >> status.md
          fi

      - name: Show Push Details
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Changed Files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^cfg/" || echo "No cfg files changed" 