name: Sync doc to Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - 'doc/**'   # 只有 doc 目录变更时触发

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Clone wiki repository
        run: |
          git clone https://github.com/Aethersailor/Custom_OpenClash_Rules.wiki.git wiki

      - name: Sync doc directory, exclude README.md
        run: |
          mkdir -p wiki/doc
          
          # 清空 wiki 的 doc 目录，但保留 README.md
          find wiki/doc -mindepth 1 -not -name README.md -exec rm -rf {} +

          # 将主仓库 doc 的内容同步过去
          rsync -av --exclude 'README.md' doc/ wiki/doc/

      - name: Commit and push changes to wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add doc
          if ! git diff --cached --quiet; then
            git commit -m "Sync doc from main repository"
            git push
