name: Backup Wiki

on:
  # 每天凌晨 3:00 备份
  schedule:
    - cron: '0 3 * * *'

  # 手动触发
  workflow_dispatch:

jobs:
  backup-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone the Wiki repository
        run: |
          git clone https://github.com/Aethersailor/Custom_OpenClash_Rules.wiki.git wiki-temp

      - name: Clear old backup and copy new files
        run: |
          rm -rf wiki
          mkdir -p wiki
          cp -r wiki-temp/*.md wiki/

      - name: Rename Home.md to README.md
        run: |
          if [ -f wiki/Home.md ]; then
            mv wiki/Home.md wiki/README.md
          fi

      - name: Replace image paths in Markdown
        run: |
          find wiki -type f -name "*.md" -exec sed -i 's#](doc/#](../doc/#g' {} +

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add wiki

          # 只有有变更时才提交
          if ! git diff --cached --quiet; then
            git commit -m "Backup Wiki $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
