name: Sync Wiki

on:
  # 定时同步：每天凌晨 3:00
  schedule:
    - cron: '0 3 * * *'
  
  # 手动触发
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Clone Wiki repository
        run: |
          git clone https://github.com/Aethersailor/Custom_OpenClash_Rules.wiki.git wiki-temp

      - name: Prepare backup directory
        run: |
          rm -rf doc/wiki/backup
          mkdir -p doc/wiki/backup
          cp -r wiki-temp/*.md doc/wiki/backup/

      - name: Replace image paths
        run: |
          find doc/wiki/backup -type f -name "*.md" -exec sed -i 's#](doc/#](../doc/#g' {} +

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add doc/wiki/backup

          # 只有有更改时才提交
          if ! git diff --cached --quiet; then
            git commit -m "Backup Wiki $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
